{% set version = "3.12.2" %}

package:
  name: constructor
  version: {{ version }}

source:
  url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
  sha256: 224fe4b51080aaefcf5272c708b3ee759d4239eaad162724931fae2123fd7286

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - constructor = constructor.main:main
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=70.1
    - setuptools-scm >=6.2
  run:
    - __{{ target_os }}
    # see for the upper conda version constrain https://github.com/conda/constructor/issues/628
    - conda >=4.6
    - conda-standalone
    - jinja2
    - python >={{ python_min }}
    - ruamel.yaml >=0.11.14,<0.19
    - jsonschema >=4
    - pillow >=3.1  # [not linux]
    - nsis >=3.08   # [win]
  run_constrained:
    - nsis >=3.08   # [unix]
    - conda-libmamba-solver !=24.11.0
    - pydantic >=2

test:
  files:
    - test_win.bat
  source_files:
    - tests
    # - examples
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - nsis * *log*  # [win]
    - pywin32  # [win]
  commands:
    - pip check
    - pytest -vv --tb=long --color=yes -k "not examples"
    # Skip for linux-aarch64 because examples use "main" channel which has no builds for that platform.
    # - set "NSIS_USING_LOG_BUILD=1"  # [win]
    # - pytest -v tests/test_examples.py  # [unix and not aarch64]
    # - test_win.bat  # [win]
    - constructor -V
  imports:
    - constructor

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.github.io/constructor

extra:
  recipe-maintainers:
    - isuruf
    - jaimergp
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
