{% set version = "3.4.4" %}

package:
  name: constructor
  version: {{ version }}

source:
  url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
  sha256: d7081751f490622785807de6a78dd8ccdf71093a947489e4af5eeb76a7bd1e21

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - constructor = constructor.main:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - __{{ target_os }}
    # see for the upper conda version constrain https://github.com/conda/constructor/issues/628
    - conda >=4.6,<23.1.0
    - python >=3.7
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1
    - nsis >=3.08      # [win]
  run_constrained:   # [unix]
    - nsis >=3.08      # [unix]

test:
  files:
    - test_win.bat
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pip
    - pytest
    - nsis * *log*  # [win]
  commands:
    - pip check
    - pytest -v tests
    # Skip for linux-aarch64 because examples use "main" channel which has no builds for that platform.
    - set "NSIS_USING_LOG_BUILD=1"  # [win]
    - python scripts/run_examples.py  # [unix and not aarch64]
    - test_win.bat  # [win]
    - constructor -V
  imports:
    - constructor

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - isuruf
    - jaimergp
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
