{% set version = "3.0.2" %}
{% set sha256 = "b46dc3ffb6a7547f84834cc888570446d94ddfd7be832f08a798f55518a30545" %}

package:
  name: constructor
  version: {{ version }}

source:
  - url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # https://github.com/conda/constructor/pull/342/commits/98968873d0c90cd90b6f9a98bc745b8c3df4acd6
      - platform_dist.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - constructor = constructor.main:main

requirements:
  host:
    - python
    - pip
  run:
    - conda >=4.6
    - python
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1  # [win]
    - nsis >=3.01  # [win]

test:
  imports:
    - constructor
  commands:
    - constructor -V
    - constructor --test .

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - msarahan
