{% set version = "1.5.5" %}
{%set sha256 = "9dfcb41a178e33c1b813eb449cdbc53640500ff22149e21c3038fb59d87ff44d" %}

package:
  name: constructor
  version: {{ version }}

source:
  fn: constructor-{{ version }}.tar.gz
  url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - libconda
    - pyyaml
    - pycosat >=0.6.1
    - pillow >=3.1  # [win]
    - nsis >=3.01   # [win]

test:
  imports:
    - constructor
  commands:
    - constructor --test

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages

extra:
  recipe-maintainers:
    - jakirkham
