{% set version = "3.4.0" %}

package:
  name: constructor
  version: {{ version }}

source:
  url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
  sha256: 0a65f564ae644cdf9f1c5d8233d5b254b958730d4d8a739db0cf3e6b65cad344
  patches:
    - 548-fix_cache_directory_creation.patch
    - 579-set-modification-time-for-ccahe-file-for-mamba.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - constructor = constructor.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - __{{ target_os }}
    - conda >=4.6
    - python >=3.6
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1  # [win]
    - nsis >=3.01,<3.08  # [win]

test:
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pillow >=3.1
    - pytest
  commands:
    - pytest -v tests
    # Skip for linux-aarch64 because examples use "main" channel which has no builds for that platform.
    - python scripts/run_examples.py  # [not aarch64]
    - constructor -V
  imports:
    - constructor

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - isuruf
    - jaimergp
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
