# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.15.3"
  python_check_max: "3.14"

package:
  name: constructor
  version: ${{ version }}

source:
  url: https://github.com/conda/constructor/archive/${{ version }}.tar.gz
  sha256: 079ab23d3c636b408d88a87afe1c858b1a0c589b48729c305e051f118d490c7b

build:
  number: 1
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
      PYTHONHASHSEED: "0"
      PIP_USE_DEPRECATED: "legacy-certs"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - constructor = constructor.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=70.1
    - setuptools-scm >=6.2
  run:
    - __${{ target_os }}
    # see for the upper conda version constrain https://github.com/conda/constructor/issues/628
    - conda >=4.6
    - conda-standalone
    - jinja2
    - jsonschema >=4
    - python >=${{ python_min }}
    - ruamel.yaml >=0.11.14,<0.19
    - if: not linux
      then:
        - pillow >=3.1
    - if: win
      then:
        - nsis
  run_constraints:
    - nsis >=3.08
    - conda-libmamba-solver !=24.11.0
    - pydantic >=2

tests:
  - python:
      imports: constructor
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - package_contents:
      site_packages:
        - constructor/data/construct.schema.json
  - files:
      # not presently used
      # recipe:
      #   - if: win
      #     then: test_win.bat
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
        - pywin32
        - if: unix
          then: shellcheck
    script:
      - pytest -vv --tb=long --color=yes -k "not examples"
      - constructor -V
      - constructor -V | python -c "import sys; v = sys.stdin.read().strip(); print(v); assert v == 'constructor ${{ version }}', f'bad version {v}'"

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  homepage: http://github.com/conda/constructor
  documentation: https://conda.github.io/constructor

extra:
  recipe-maintainers:
    - isuruf
    - jaimergp
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
