bot:
  inspection: hint-grayskull
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_install_tool: pixi
noarch_platforms:
  - linux_64
  - win_64
  - osx_64
